---
- name: check
  uri:
    url: "https://haveibeenpwned.com/api/v3/breachedaccount/{{ item.mail }}"
    validate_certs: false
    method: GET
    headers:
      hibp-api-key: "{{ apikey }}"
  ignore_errors: yes
  register: result

- set_fact:
    info3: "{{ result.json | map(attribute='Name') | join(',') }}"
  when: result is succeeded

- copy: content="{{ info3 }}" dest=/base

- name: Ansible replace PDL
  replace:
    path: base
    regexp: 'PDL'
    replace: "world"

- name: telegram
  uri:
    url: https://api.telegram.org/bot1343317346:{{telegram}}/sendMessage?chat_id=-1001437610160&text={{item.mail}},{{info4}}
  when: result is succeeded
